spring.application.name=tfgcine
server.port=8080
server.address=0.0.0.0
tmdb.api.key=${TMDB_API_KEY}
tmdb.api.base=https://api.themoviedb.org/3
tmdb.image.base=https://image.tmdb.org/t/p/w500

tmdb.api.language.primary=es-ES
tmdb.api.language.fallback=en-US

#spring.mustache.suffix=.mustache

# TMDB Image URLs
tmdb.image.poster=https://image.tmdb.org/t/p/w500
tmdb.image.backdrop=https://image.tmdb.org/t/p/original
